# Generated by Django 5.2.14 on 2026-05-29 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardapioSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataInicio', models.DateField(verbose_name='Data de início')),
                ('dataFim', models.DateField(verbose_name='Data de fim')),
                ('status', models.CharField(max_length=20, verbose_name='Status do cardápio')),
            ],
            options={
                'verbose_name': 'Cardápio Semanal',
                'verbose_name_plural': 'Cardápios Semanais',
            },
        ),
        migrations.CreateModel(
            name='DiaSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome do dia')),
            ],
            options={
                'verbose_name': 'Dia da Semana',
                'verbose_name_plural': 'Dias da Semana',
            },
        ),
        migrations.CreateModel(
            name='TipoRefeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome do tipo de refeição')),
                ('horarioInicio', models.TimeField(verbose_name='Horário de início')),
                ('horarioFim', models.TimeField(verbose_name='Horário de fim')),
            ],
            options={
                'verbose_name': 'Tipo de Refeição',
                'verbose_name_plural': 'Tipos de Refeição',
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome do tipo de usuário')),
                ('nivelAcesso', models.CharField(max_length=20, verbose_name='Nível de acesso')),
            ],
            options={
                'verbose_name': 'Tipo de Usuário',
                'verbose_name_plural': 'Tipos de Usuário',
            },
        ),
        migrations.CreateModel(
            name='Refeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pratoPrincipal', models.CharField(max_length=200, verbose_name='Prato principal')),
                ('opcaoVegetariana', models.CharField(max_length=200, verbose_name='Opção vegetariana')),
                ('acompanhamento', models.CharField(max_length=200, verbose_name='Acompanhamento')),
                ('salada', models.CharField(max_length=200, verbose_name='Salada')),
                ('sobremesa', models.CharField(max_length=200, verbose_name='Sobremesa')),
                ('suco', models.CharField(max_length=100, verbose_name='Suco')),
                ('cardapioSemanal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cardapiosemanal', verbose_name='Cardápio semanal')),
                ('diaSemana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.diasemana', verbose_name='Dia da semana')),
                ('tipoRefeicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tiporefeicao', verbose_name='Tipo de refeição')),
            ],
            options={
                'verbose_name': 'Refeição',
                'verbose_name_plural': 'Refeições',
            },
        ),
        migrations.CreateModel(
            name='MediaAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notaMedia', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Nota média')),
                ('quantidadeAvaliacoes', models.IntegerField(verbose_name='Quantidade de avaliações')),
                ('refeicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.refeicao', verbose_name='Refeição relacionada')),
            ],
            options={
                'verbose_name': 'Média de Avaliação',
                'verbose_name_plural': 'Médias de Avaliações',
            },
        ),
        migrations.CreateModel(
            name='FotoRefeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlFoto', models.CharField(max_length=300, verbose_name='URL da foto')),
                ('legenda', models.CharField(max_length=200, verbose_name='Legenda da foto')),
                ('dataUpload', models.DateTimeField(verbose_name='Data de upload')),
                ('refeicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.refeicao', verbose_name='Refeição relacionada')),
            ],
            options={
                'verbose_name': 'Foto da Refeição',
                'verbose_name_plural': 'Fotos das Refeições',
            },
        ),
        migrations.CreateModel(
            name='CardapioDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data do cardápio')),
                ('refeicaoAlmoco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardapio_almoco', to='app.refeicao', verbose_name='Refeição do almoço')),
                ('refeicaoJantar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardapio_jantar', to='app.refeicao', verbose_name='Refeição do jantar')),
            ],
            options={
                'verbose_name': 'Cardápio do Dia',
                'verbose_name_plural': 'Cardápios do Dia',
            },
        ),
        migrations.CreateModel(
            name='RestricaoAlimentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da restrição')),
                ('descricao', models.TextField(verbose_name='Descrição da restrição')),
                ('refeicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.refeicao', verbose_name='Refeição relacionada')),
            ],
            options={
                'verbose_name': 'Restrição Alimentar',
                'verbose_name_plural': 'Restrições Alimentares',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do usuário')),
                ('matricula', models.CharField(max_length=20, unique=True, verbose_name='Matrícula do usuário')),
                ('email', models.CharField(max_length=100, verbose_name='Email do usuário')),
                ('senha', models.CharField(max_length=128, verbose_name='Senha do usuário')),
                ('tipoUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipousuario', verbose_name='Tipo de usuário')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='Sugestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da sugestão')),
                ('descricao', models.TextField(verbose_name='Descrição da sugestão')),
                ('dataHora', models.DateTimeField(verbose_name='Data e hora da sugestão')),
                ('status', models.CharField(max_length=20, verbose_name='Status da sugestão')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Usuário que sugeriu')),
            ],
            options={
                'verbose_name': 'Sugestão',
                'verbose_name_plural': 'Sugestões',
            },
        ),
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do aviso')),
                ('mensagem', models.TextField(verbose_name='Mensagem do aviso')),
                ('dataPublicacao', models.DateTimeField(verbose_name='Data de publicação')),
                ('dataExpiracao', models.DateTimeField(verbose_name='Data de expiração')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Usuário que publicou')),
            ],
            options={
                'verbose_name': 'Aviso',
                'verbose_name_plural': 'Avisos',
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(verbose_name='Nota da avaliação')),
                ('comentario', models.TextField(verbose_name='Comentário da avaliação')),
                ('dataHora', models.DateTimeField(verbose_name='Data e hora da avaliação')),
                ('refeicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.refeicao', verbose_name='Refeição avaliada')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Usuário que avaliou')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
            },
        ),
    ]
