# Generated by Django 5.2.14 on 2026-06-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refeicao',
            name='acompanhamento',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Acompanhamento'),
        ),
        migrations.AlterField(
            model_name='refeicao',
            name='opcaoVegetariana',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Opção vegetariana'),
        ),
        migrations.AlterField(
            model_name='refeicao',
            name='salada',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Salada'),
        ),
        migrations.AlterField(
            model_name='refeicao',
            name='sobremesa',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sobremesa'),
        ),
        migrations.AlterField(
            model_name='refeicao',
            name='suco',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Suco'),
        ),
    ]
